# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - roust-dev.tms.artlogics.ru
  backends:
    - path: /
      serviceName: front
      servicePort: 80
    - path: /api
      serviceName: back
      servicePort: 5000
    - path: /tasks
      serviceName: tasks
      servicePort: 7000
    - path: /state
      serviceName: tasks
      servicePort: 7000
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx

