# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - roust.tms.artlogics.ru
  backends:
    - path: /
      serviceName: front
      servicePort: 80
    - path: /api
      serviceName: back
      servicePort: 5000
    - path: /tasks
      serviceName: tasks
      servicePort: 7000
    - path: /state
      serviceName: tasks
      servicePort: 7000
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    - secretName: roust.tms.artlogics.ru-tls
      hosts:
        - roust.tms.artlogics.ru
