# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.artlogics.ru/tms-lite-roust-front
  tag: prod
  pullPolicy: IfNotPresent
  imagePullSecrets: gitlab-registry
service:
  name: front
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
ingress:
  enabled: false
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - front
        topologyKey: "kubernetes.io/hostname"
