# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.artlogics.ru/tms-lite-roust-tasks
  tag: test1
  pullPolicy: IfNotPresent
  imagePullSecrets: gitlab-registry
env:
  ASPNETCORE_ENVIRONMENT: "Test1"
service:
  name: tasks
  type: ClusterIP
  externalPort: 7000
  internalPort: 8080

resources:
  limits:
    cpu: 500m
  # memory: 800Mi
  requests:
    cpu: 300m
  # memory: 700Mi
 
metrics:
  scrape: true
  path: "/state"

ingress:
  enabled: false
